package com.tatsam.demo.priority.entity;

import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.springframework.data.annotation.LastModifiedDate;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;


//this is the entity object  which maps to the below mentioned table in DB
@Entity
@Data
@Table(name = "USER_DETAILS")
public class AppUser implements Serializable {

    //Primary key for this table which is a auto generated by spring data
    @Id  //managed my java persistence
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "n_user_id")
    private Long user_id;

    @Column(name = "c_first_name",nullable = false)
    private String firstName;

    @Column(name = "c_last_name")
    private String lastName;

    @Column(name = "c_email",unique = true)
    private String email;

    @Column(name = "n_age")
    private Integer age;

    @Column(name = "c_city",nullable = false)
    private String cityName;

    @Column(name = "mobile_number",nullable = false,unique = true,length = 13)
    private String mobileNumber;

    @Temporal(value = TemporalType.TIMESTAMP)
    @Column(name = "t_created_at",updatable = false)
    @CreationTimestamp
    private LocalDateTime createdAt;


    @Temporal(value = TemporalType.TIMESTAMP)
    @LastModifiedDate
    @Column(name = "t_lupdated_at",updatable = false)
    private LocalDateTime lastUpdatedAt;

    //bi-directional
    @OneToMany(mappedBy = "userList")
    private List<UserAttribute> userAreasList;
}
